server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank1?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    #    password:
    #    连接超时时间：毫秒
    #    Redis默认情况下有16个分片
    database: 0
    lettuce:
      pool:
        #        连接池最大连接数（使用负值表示没有限制）,默认8
        max-active: 8
        #        连接池最大阻塞等待时间（使用负数表示没有限制），默认-1
        #        连接池中的最大空闲连接数 默认8
        max-idle: 8
        #        连接池中最小的默认空闲连接数 默认 0
        min-idle: 0
    port: 6379